In [1]:
import numpy as np
from joblib import load
model=load('Boston.joblib')

In [2]:
# now how to use the model....from original notebook..use prepared_data[0]...and copy from there and paste here..
#prepared_data[0]=array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
#       -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
#       -0.97491834,  0.41164221, -0.86091034])

In [3]:
features=np.array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

In [4]:
model.predict([features])   #this predicted the price.

array([22.218])

In [5]:
features=np.array([-0.42292925, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
        5.3494109, -0.52225911,  0.37882487, -0.5429938 , -0.74402708,
        0.52982668,  0.45343469, -0.81939807])
       

In [6]:
model.predict([features])  #RM = 5.3494109 this was important feature...as we have change it ..there is a huge change in price.

array([38.793])

# LETS TRY BY GIVING ACTUAL VALUES OF FEATURES TO THE MODEL FOR PREDICTION.....

In [7]:
# Lets try with actucal values of features.....actucal data...lets cross check
#CRIM,    ZN , INDUS , CHAS , NOX,   RM,     AGE,    DIS,      RAD,   TAX,   PITRATIO,   B,      LSTAT    MEDV
#0.01501, 80.0 ,2.01,  0,     0.435, 6.635,  29.7,  8.3440,     4,    280,    17.0,    390.94   ,5.99,    24.5
#4.87141, 0.0, 18.10  ,0,     0.614, 6.484,  93.6,  2.3053,     24,   666,    20.2,    396.21,   18.68,   16.7

In [8]:
features=np.array([0.01501, 80.0 ,2.01, 0, 0.435, 6.635,  29.7,  8.3440, 4,280,17.0,390.94 ,5.99])

In [9]:
model.predict([features])   # wonderful, prediction of price.

array([24.08])

In [10]:
features=np.array([4.87141, 0.0, 18.10,0, 0.614, 6.484,93.6,2.3053,24,666,20.2,396.21,18.68])

In [11]:
model.predict([features])   # 16.7-----> predicted price 24.217....bit diff...but no issue as we were dealing with very small
                            # dataset.

array([24.217])

In [12]:
#-----------------------------------------------------------------------------------------------------------------------------#